### ISSUE TITLE
Fix "double dipping/counting" of courses under major plan requirements

### ISSUE THREAD

**Issue by richardwu** [theRoughCode/WatsMyMajorBeta#71] opened 2018-09-12 03:30 UTC
e.g. CS 350 is double-counted as itself and "Choose 3 of ... CS 340-398"
![image](https://user-images.githubusercontent.com/10563314/45400555-a34df400-b61a-11e8-8df2-4bf37cc0c07d.png)

**Comment by theRoughCode** [comment] 2018-09-12 13:30
Closing as duplicate of #35

**Closed by theRoughCode** 2018-09-12 13:30 UTC
